{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-coroutines-core/1.3.8-1.4.0-rc/kotlinx-coroutines-core-1.3.8-1.4.0-rc.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-coroutines-core",
    "version": "1.3.8-1.4.0-rc",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "wcxqakrxfbazpnyrjy6b4a7cfi"
    }
  },
  "variants": [
    {
      "name": "jvm-api",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.0-rc"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.0-rc"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-coroutines-core-jvm-1.3.8-1.4.0-rc.jar",
          "url": "kotlinx-coroutines-core-jvm-1.3.8-1.4.0-rc.jar",
          "size": 1668476,
          "sha512": "8ca110f4bca19f479b4bfa687459cfb92685d7890f7587eee7ff199d9a6bbbb076fac27343e8e6b27560511257fef219331b84de372240d5b0be9a062ccbe2cd",
          "sha256": "2ee31e39d75091d0bae9777c35c47f929f5a4294d3aa1a0229742192d0b0ad1e",
          "sha1": "0002c9c533543d2ace69b1e64918d159264a50e5",
          "md5": "3f686aa62921d3f17783729d2a0ad4f9"
        }
      ]
    },
    {
      "name": "jvm-runtime",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.0-rc"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.0-rc"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-coroutines-core-jvm-1.3.8-1.4.0-rc.jar",
          "url": "kotlinx-coroutines-core-jvm-1.3.8-1.4.0-rc.jar",
          "size": 1668476,
          "sha512": "8ca110f4bca19f479b4bfa687459cfb92685d7890f7587eee7ff199d9a6bbbb076fac27343e8e6b27560511257fef219331b84de372240d5b0be9a062ccbe2cd",
          "sha256": "2ee31e39d75091d0bae9777c35c47f929f5a4294d3aa1a0229742192d0b0ad1e",
          "sha1": "0002c9c533543d2ace69b1e64918d159264a50e5",
          "md5": "3f686aa62921d3f17783729d2a0ad4f9"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-metadata/1.3.8-1.4.0-rc/kotlinx-coroutines-core-metadata-1.3.8-1.4.0-rc.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-metadata",
        "version": "1.3.8-1.4.0-rc"
      }
    },
    {
      "name": "metadata-commonMainMetadataElements",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-metadata/1.3.8-1.4.0-rc/kotlinx-coroutines-core-metadata-1.3.8-1.4.0-rc.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-metadata",
        "version": "1.3.8-1.4.0-rc"
      }
    }
  ]
}
