{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-html/0.7.1-1.4-M3/kotlinx-html-0.7.1-1.4-M3.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-html",
    "version": "0.7.1-1.4-M3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "axf5xql5yjdnbk5lpg75ipusva"
    }
  },
  "variants": [
    {
      "name": "jvm-api",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kotlinx-html-jvm-0.7.1-1.4-M3.jar",
          "url": "kotlinx-html-jvm-0.7.1-1.4-M3.jar",
          "size": 785522,
          "sha512": "cf1196d9b96ea6b7a3b84f8854e59cb60f3c5708438cf95e20a4f9cdc8e5ce0fc2fc6e67dd753fbb50a9c7b6bf5e03592235fe7d925fc7bef3c757c00995d52a",
          "sha256": "55c25d5fbc0cd0e82ee4471c48cdcfb0d8554c41600070a93ef4bc0ac51460cc",
          "sha1": "884c9e950772ac64982db1248f8e5b58f319f4a5",
          "md5": "22284e647b0a3e7f35cde1f606a617c9"
        }
      ]
    },
    {
      "name": "jvm-runtime",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4-M3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4-M3"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-html-jvm-0.7.1-1.4-M3.jar",
          "url": "kotlinx-html-jvm-0.7.1-1.4-M3.jar",
          "size": 785522,
          "sha512": "cf1196d9b96ea6b7a3b84f8854e59cb60f3c5708438cf95e20a4f9cdc8e5ce0fc2fc6e67dd753fbb50a9c7b6bf5e03592235fe7d925fc7bef3c757c00995d52a",
          "sha256": "55c25d5fbc0cd0e82ee4471c48cdcfb0d8554c41600070a93ef4bc0ac51460cc",
          "sha1": "884c9e950772ac64982db1248f8e5b58f319f4a5",
          "md5": "22284e647b0a3e7f35cde1f606a617c9"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../kotlinx-html-common/0.7.1-1.4-M3/kotlinx-html-common-0.7.1-1.4-M3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-html-common",
        "version": "0.7.1-1.4-M3"
      }
    }
  ]
}
